config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'application#index'

  get 'whats-new', to: 'blog_posts#index'

  resources :blog_posts, path: '/whats-new/blog', only: %i[index show] do
    resources :comments, only: %i[create]
  end
  resources :team_members, path: 'team', only: %i[show]
  resources :research_partners, path: 'partner', only: %i[show]
  resources :board_members, path: 'board', only: %i[show]
  resources :contributors, only: %i[show]
  resources :news, only: %i[index show]
  resources :research_reports, only: %i[show] do
    resources :sub_reports, only: %i[show], controller: 'sub_research_reports'
  end
  resources :prototypes, only: %i[show]

  get 'contact-us', to: 'contact_forms#new', as: :new_contact_forms
  post 'contact-us', to: 'contact_forms#create', as: :contact_forms

  get 'comments/:id/publish', to: 'comments#publish'

  post :expire_cache, to: 'application#expire_cache'

  get 'about-us/governance', to: 'governance#show'
  get 'about-us/meet-the-team', to: 'meet_the_team#show'
  get 'about-us/our-research-partners', to: 'our_research_partners#show'

  get 'evidence/evidence-store', to: redirect('https://wwc-evidence.herokuapp.com/')

  resources :sections, path: '/', only: :show do
    resources :pages, path: '/', only: :show
  end
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ContentfulModel::Base
  include Draper::Decoratable
  
  def self.preview
    ContentfulModel.use_preview_api = true
    self
  end
end

app/models/blog_post.rb
# frozen_string_literal: true

class BlogPost < ApplicationRecord
  self.content_type_id = 'blogPost'
  
  belongs_to_many :comments
end

app/models/board_member.rb
class BoardMember < ApplicationRecord
  self.content_type_id = 'boardMember'
  
  belongs_to_many :blog_posts
  
  def path
    "/board/#{slug}"
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
  self.content_type_id = 'comment'
  
  has_one :associated_record, class_name: 'BlogPost'
  
  def self.create(params)
    comment = super(params)
    CommentMailer.with(comment_id: comment.id).comment_alert.deliver_now
    comment
  end
  
  def contentful_url
    "https://app.contentful.com/spaces/#{ENV['CONTENTFUL_SPACE_ID']}/entries/#{id}"
  end
end

app/models/contact_form.rb
class ContactForm < MailForm::Base
  attribute :name, validate: true
  attribute :email, validate: /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i

  attribute :message
  attribute :tel, captcha: true

  def headers
    {
      subject: 'Contact Form',
      to: ENV['CSC_CONTACT_EMAIL'],
      from: %("#{name}" <#{email}>)
    }
  end
end

app/models/contributor.rb
class Contributor < ApplicationRecord
  self.content_type_id = 'contributor'
  
  def path
    "/contributors/#{slug}"
  end
end

app/models/page.rb
class Page < ApplicationRecord
  self.content_type_id = 'page'
  
  has_one :section
end

app/models/research_partner.rb
class ResearchPartner < ApplicationRecord
  self.content_type_id = 'researchPartner'

  belongs_to_many :blog_posts

  def path
    "/partner/#{slug}"
  end
end

app/models/section.rb
class Section < ApplicationRecord
  self.content_type_id = 'section'
  
  belongs_to_many :pages
end

app/models/stakeholder_panel.rb
class StakeholderPanel < ApplicationRecord
  self.content_type_id = 'stakeholderPanel'
end

app/models/team_member.rb
class TeamMember < ApplicationRecord
  self.content_type_id = 'teamMember'
  
  belongs_to_many :blog_posts
  
  def path
    "/team/#{slug}"
  end
end

app/controllers/blog_posts_controller.rb
# frozen_string_literal: true

class BlogPostsController < ApplicationController
  include ContentfulController
  
  append_before_action :fetch_section

  def index; end

  def show; end
  
  private
  
  def list
    BlogPost.all.order(date: :desc).load
  end
  
  def fetch_section
    @section = Section.find_by(slug: 'whats-new').load.first
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  helper ContentfulRails::MarkdownHelper

  def create
    # We can't do normal Rails-y validation here because Contentful has to send
    # content to the server first, and also allows us to save drafts with missing
    # fields.
    if comment_params[:name].blank? || comment_params[:email].blank?
      flash[:alert] = 'Some required fields were missing'
      @blog_post = @blog_post.decorate
      render 'blog_posts/show'
    else
      @comment = Comment.create(comment_params.to_h.symbolize_keys)
      redirect_to blog_post_path(params[:blog_post_id]), notice: 'Your comment has been submitted!'
    end
  end

  def publish
    comment = Comment.preview.find_by(id: params[:id]).load.first
    comment.publish
    redirect_to blog_post_path(id: comment.associated_record.slug), notice: 'Comment Published!'
  end

  private

  def comment_params
    params.require(:comment)
          .permit(:name, :email, :organisation, :comment)
          .merge(associated_record: blog_post)
  end

  def blog_post
    @blog_post ||= BlogPost.find_by(slug: params[:blog_post_id]).load.first
  end
end

app/controllers/dashboard_controller.rb
# frozen_string_literal: true

class DashboardController < ApplicationController

  def index; end

  def show; end
  
end

app/controllers/evidence_controller.rb
# frozen_string_literal: true

class EvidenceController < ApplicationController

  def index; end

  def show; end
  
end

app/controllers/governance_controller.rb
class GovernanceController < PagesController
  include ContentfulController

  append_before_action :load_additional_content

  def show; end

  def params
    super.merge(section_id: 'about-us', id: 'governance')
  end

  private

  def load_additional_content
    @board_members = BoardMember.all.load
    # @team_members = TeamMember.all.load
    @stakeholder_panels = StakeholderPanel.all.load
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  include ContentfulController

  prepend_before_action :fetch_research_reports, if: -> { params[:id] == 'research' }
  prepend_before_action :fetch_prototypes, if: -> { params[:id] == 'co-designing-with-partners' }

  def show; end

  private

  def fetch_section
    @section = Section.load_children(10).find_by(slug: params[:section_id]).load.first
    raise(ActionController::RoutingError, 'Not Found') if @section.nil?
  end

  def load_content
    check_preview
    fetch_section
    content = @section.pages.find { |p| p.slug == params[:id] }
    raise(ActionController::RoutingError, 'Not Found') if content.nil?
    @page = content.decorate
  end

  def fetch_research_reports
    @research_reports = ResearchReport.all.load
  end

  def fetch_prototypes
    @prototypes = Prototype.all.load
  end
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  include ContentfulController

  def show; end
end

app/controllers/sections_controller.rb
class SectionsController < ApplicationController
  include ContentfulController
  
  append_before_action :load_pages

  def show; end
  
  private
  
  def load_pages
    @pages = @section.pages.sort_by(&:title)
  end
end

app/controllers/who_we_are_controller.rb
class WhoWeAreController < PagesController
  include ContentfulController
  
  append_before_action :load_additional_content
  
  def show; end
  
  def params
    super.merge(section_id: 'about-us', id: 'who-we-are')
  end
  
  private
  
  def load_additional_content
    @board_members = BoardMember.all.load
    @team_members = TeamMember.all.load
    @stakeholder_panels = StakeholderPanel.all.load
  end
  
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
  def twitter
    tweet = WhatWorksCentre::Twitter.instance.latest_tweet
    return nil unless tweet
    content_tag :div, class: 'twitter' do
      output = content_tag(:span, link_to(tweet.attrs[:full_text], tweet.uri.to_s), id: 'tweet_cont')
      output << content_tag(:span, link_to('View Tweet', tweet.uri.to_s), id: 'tweet_link')
      output
    end
  end
end

app/views/dashboard/index.haml
.container
  .full_width

    %h1
      Intensive Family Preservation Programmes (IFPPs)

    %h4
      IFPPs are interventions aimed at families in crisis, where there is an imminent risk of children entering care. They are programmes that work intensively with families to try to avoid out-of-home placement.
    %p
      %strong
        Summary
      %br
      A rapid response (within 24 hours of referral) and intensive (4-6 week) programme that provides a range of services to families in crisis, tailored to the family’s needs.

    %p
      %strong
        Outcomes
      %br
      Entry to care
      %br
      Family functioning
    
    %p
      %strong
        Effective for
      %br
      Lower-risk families where concerns are not related to abuse or neglect
    
    %p        
      %strong
        Delivered by
      %br
      Social workers

.container
  .full_width

    %h2
      What is this?
    %p
      Intensive Family Preservation Programmes (IFPPs) are interventions aimed at families in crisis, where there is an imminent risk of children entering care. They are programmes that works intensively with families to try to avoid out-of-home placement.
    
    %h3
      How is it meant to work?
    %p
      This a rapid response (within 24 hours of referral) and intensive (4-6 week) programme that provides a range of services to families in crisis, tailored to the family’s needs. Typically, the programme includes parenting training, therapeutic input for adults and/or children and practical or financial support. By intervening at times of crisis, IFPPs seek to stabilise families and help them to provide “good-enough” parenting, as well as helping to build resilience in case of future crises.
    %p
      In the US, this is referred to as the ‘Homebuilders’ model. In the UK, an IFPP model called ‘Option 2’ has been developed specifically for families where there are serious child protection concerns related to drug or alcohol misuse.
    %h3
      What are the evaluated outcomes?
    %ul
      %li
        Entry to care
      %li
        Family functioning
    %h3
      How effective is it overall?

    %p
      Entry to care – Overall, IFPPs were not effective in reducing entry to care for families in crisis. This is based on moderate-quality evidence.
    %p
      Family functioning – IFPPs had a low to moderate effect on family functioning. This is based on low-quality evidence.

.container
  .full_width

    %h2
      When, where and who does this work for?
    %h3
      Where has it been implemented?
    %p
      The majority of the studies have been carried out in the US. There has been one study in the UK. 
    %h3
      When does it work best?
    %p
      If people delivering intervention have small caseloads.
    %p
      Intensity is more important than duration of the intervention.
    %h3
      Who does it work for?
    %p
      %strong
        For reducing entry to care, IFPPS is:
    %p
      %strong
        Not effective for
      %br
      Families where the key concerns relate to abuse and neglect
    %p
      %strong
        Effective for
      %br
      Lower-risk families where concerns are not related to abuse and neglect
    %p
      %strong
        Has a negative effect for
      %br
      Families initially not judged at risk of children entering care
    %p
      %strong
        This intervention has been shown to be more effective for
      %br
      Boys compared to girls
      %br
      Younger compared to older children

.container
  .full_width

    %h2
      How does it work in practice?
    %p
      The evidence suggests that IFPPs can help lower-risk families whose problems are not linked to abuse and neglect. They can help to avoid risk escalating, leading to removal of children.
    %p
      There was little evidence about the mechanisms for this.
    %h3
      How is this implemented?

    %p
      %strong
        Who can deliver it?
      %br
      Social workers
    %p
      %strong
        What are the training requirements?
      %br
      DK
    %p
      %strong
        How are the practitioners supervised?
      %br
      DK
    %p
      %strong
        What are the systems for maintaining fidelity?
      %br
      DK
    %p
      %strong
        What else supports good implementation?
      %br
      Limited caseloads for those delivering the intervention
    %p
      %strong
        Useful contacts
      %br
      Sheffield Alcohol Support Service
      %br
      Cardiff and Vale of Glamorgan

    %h3
      What are the costs and benefits?
    %p
      There is no evidence on the cost-benefit of this intervention.

    %h3
      What else do I need to consider?
    %p
      Before implementing this intervention it is important to
    %ul
      %li
        Be clear about who you are targeting, as the intervention is not effective for all types of families
      %li
        Ensure that the people delivering the intervention can provide a high- intensity of service – this will mean having relatively small caseloads
      %li
        This intervention may not help you reduce overall entry to care, but may help to improve family functioning for some families

app/views/evidence/dashboard.haml
%section.background.hero
  .container

%section.dashboard
  .container

    / .items
    /   .tags
    /     %span
    /       Domestic abuse
    /     %span
    /       Drug or alcohol abuse
    /     %span
    /       Emotional abuse
    /     %span
    /       Exploitation and radicalisation
    /     %span.selected
    /       Gangs
    /     %span
    /       Mental health
    /     %span
    /       Neglect
    /     %span.selected
    /       Physical abuse
    /     %span
    /       Sexual abuse
    /     %span.selected
    /       Youth offending

    .menu.item
      .details
        Intervention
      .outcome_wrap
        .outcome
          Evaluation
        .score
          .effect
            Effect
          .evidence
            Evidence

    = link_to '', class: 'item' do
      .details
        %h3
          Intensive Family Preservation Programmes
        %p
          Aimed at families in crisis, where there is an imminent risk of children entering care and to avoid out-of-home placement.
      .outcome_wrap
        .outcome
          %strong
            Family functioning
          %p
            Moderate effect, low evidence
        .score
          .effect
            .spot.fill
            .spot.fill
            .spot
          .evidence
            .spot.fill
            .spot
            .spot
      .outcome_wrap
        .outcome
          %strong
            Entry to care
          %p
            No effect, moderate evidence
        .score
          .effect
            .spot
            .spot
            .spot
          .evidence
            .spot.fill
            .spot.fill
            .spot

    = link_to '', class: 'item' do
      .details
        %h3
          Interventions to improve maternal-child attachment
        %p
          Improve attachment between mothers and their babies in the early stages of the children’s lives.
      .outcome_wrap
        .outcome
          %strong
            Maternal sensitivity
          %p
            High effect, hgh evidence.
        .score
          .effect
            .spot.fill
            .spot.fill
            .spot.fill
          .evidence
            .spot.fill
            .spot.fill
            .spot.fill
      .outcome_wrap
        .outcome
          %strong
            Reflective functioning
          %p
            High effect, high evidence.
        .score
          .effect
            .spot.fill
            .spot.fill
            .spot.fill
          .evidence
            .spot.fill
            .spot.fill
            .spot.fill

    = link_to '', class: 'item' do
      .details
        %h3
          IFFPS
        %p
          Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
          tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam.
      .outcome_wrap
        .outcome
          %strong
            Functioning
          %p
            Negative effect, high evidence
        .score
          .effect
            .spot.fill.negative
          .evidence
            .spot.fill
            .spot.fill
            .spot.fill
      .outcome_wrap
        .outcome
          %strong
            Entry
          %p
            Low effect, low evidence
        .score
          .effect
            .spot.fill
            .spot
            .spot
          .evidence
            .spot.fill
            .spot
            .spot

    = link_to '', class: 'item' do
      .details
        %h3
          Intensive Family Preservation Programmes
        %p
          Aimed at families in crisis, where there is an imminent risk of children entering care and to avoid out-of-home placement.
      .outcome_wrap
        .outcome
          %strong
            Family functioning
          %p
            Moderate effect, low evidence
        .score
          .effect
            .spot.fill
            .spot
            .spot
          .evidence
            .spot.fill
            .spot.fill
            .spot.fill
      .outcome_wrap
        .outcome
          %strong
            Entry to care
          %p
            No effect, low evidence
        .score
          .effect
            .spot.fill
            .spot.fill
            .spot.fill
          .evidence
            .spot.fill
            .spot
            .spot

    = link_to '', class: 'item' do
      .details
        %h3
          Intensive Family Preservation Programmes
        %p
          Aimed at families in crisis, where there is an imminent risk of children entering care and to avoid out-of-home placement.
      .outcome_wrap
        .outcome
          %strong
            Family functioning
          %p
            Moderate effect, low evidence
        .score
          .effect
            .spot.fill
            .spot
            .spot
          .evidence
            .spot.fill
            .spot.fill
            .spot.fill
      .outcome_wrap
        .outcome
          %strong
            Entry to care
          %p
            No effect, low evidence
        .score
          .effect
            .spot.fill
            .spot.fill
            .spot.fill
          .evidence
            .spot.fill
            .spot
            .spot

    = link_to '', class: 'item' do
      .details
        %h3
          Intensive Family Preservation Programmes
        %p
          Aimed at families in crisis, where there is an imminent risk of children entering care and to avoid out-of-home placement.
      .outcome_wrap
        .outcome
          %strong
            Family functioning
          %p
            Moderate effect, low evidence
        .score
          .effect
            .spot.fill
            .spot
            .spot
          .evidence
            .spot.fill
            .spot.fill
            .spot.fill
      .outcome_wrap
        .outcome
          %strong
            Entry to care
          %p
            No effect, low evidence
        .score
          .effect
            .spot.fill
            .spot.fill
            .spot.fill
          .evidence
            .spot.fill
            .spot
            .spot

    = link_to '', class: 'item' do
      .details
        %h3
          Intensive Family Preservation Programmes
        %p
          Aimed at families in crisis, where there is an imminent risk of children entering care and to avoid out-of-home placement.
      .outcome_wrap
        .outcome
          %strong
            Family functioning
          %p
            Moderate effect, low evidence
        .score
          .effect
            .spot.fill
            .spot
            .spot
          .evidence
            .spot.fill
            .spot.fill
            .spot.fill
      .outcome_wrap
        .outcome
          %strong
            Entry to care
          %p
            No effect, low evidence
        .score
          .effect
            .spot.fill
            .spot.fill
            .spot.fill
          .evidence
            .spot.fill
            .spot
            .spot

    = link_to '', class: 'item' do
      .details
        %h3
          Intensive Family Preservation Programmes
        %p
          Aimed at families in crisis, where there is an imminent risk of children entering care and to avoid out-of-home placement.
      .outcome_wrap
        .outcome
          %strong
            Family functioning
          %p
            Moderate effect, low evidence
        .score
          .effect
            .spot.fill
            .spot
            .spot
          .evidence
            .spot.fill
            .spot.fill
            .spot.fill
      .outcome_wrap
        .outcome
          %strong
            Entry to care
          %p
            No effect, low evidence
        .score
          .effect
            .spot.fill
            .spot.fill
            .spot.fill
          .evidence
            .spot.fill
            .spot
            .spot

    = link_to '', class: 'item' do
      .details
        %h3
          Intensive Family Preservation Programmes
        %p
          Aimed at families in crisis, where there is an imminent risk of children entering care and to avoid out-of-home placement.
      .outcome_wrap
        .outcome
          %strong
            Family functioning
          %p
            Moderate effect, low evidence
        .score
          .effect
            .spot.fill
            .spot
            .spot
          .evidence
            .spot.fill
            .spot.fill
            .spot.fill
      .outcome_wrap
        .outcome
          %strong
            Entry to care
          %p
            No effect, low evidence
        .score
          .effect
            .spot.fill
            .spot.fill
            .spot.fill
          .evidence
            .spot.fill
            .spot
            .spot

app/views/evidence/list.haml
%section.background.hero
  .container

%section.dashboard
  .container

    / .items
    /   .tags
    /     %span
    /       Domestic abuse
    /     %span
    /       Drug or alcohol abuse
    /     %span
    /       Emotional abuse
    /     %span
    /       Exploitation and radicalisation
    /     %span.selected
    /       Gangs
    /     %span
    /       Mental health
    /     %span
    /       Neglect
    /     %span.selected
    /       Physical abuse
    /     %span
    /       Sexual abuse
    /     %span.selected
    /       Youth offending


    .indent
      = link_to '', class: 'item' do
        .item
          .details
            %h3
              Intensive Family Preservation Programmes
            %p
              Intensive Family Preservation Programmes (IFPPs) are interventions aimed at families in crisis, where there is an imminent risk of children entering care. They are programmes that work intensively with families to try to avoid out-of-home placement.
          .measurement
            .of-effect
              %label
                Effect
              .spot.measure.fill
              .spot.measure.fill
              .spot.measure.fill
            .negative
              %label
                Negative
              .spot.measure
            .of-evidence
              %label
                Evidence
              .spot.measure.fill
              .spot.measure.fill
              .spot.measure

      = link_to '', class: 'item' do
        .item
          .details
            %h3
              IFPP
            %p
              Intensive Family Preservation Programmes (IFPPs) are interventions aimed at families in crisis, where there is an imminent risk of children entering care. They are programmes that work intensively with families to try to avoid out-of-home placement.
          .measurement
            .of-effect
              %label
                Effect
              .spot.measure.fill
              .spot.measure
              .spot.measure
            .negative.fill
              %label
                Negative
              .spot.measure
            .of-evidence
              %label
                Evidence
              .spot.measure.fill
              .spot.measure
              .spot.measure

      = link_to '', class: 'item' do
        .item
          .details
            %h3
              Family Preservation
            %p
              Intensive Family Preservation Programmes (IFPPs) are interventions aimed at families in crisis, where there is an imminent risk of children entering care. They are programmes that work intensively with families to try to avoid out-of-home placement.
          .measurement
            .of-effect
              %label
                Effect
              .spot.measure.fill
              .spot.measure.fill
              .spot.measure.fill
            .negative
              %label
                Negative
              .spot.measure
            .of-evidence
              %label
                Evidence
              .spot.measure.fill
              .spot.measure.fill
              .spot.measure.fill

      = link_to '', class: 'item' do
        .item
          .details
            %h3
              Intensive Programmes
            %p
              Intensive Family Preservation Programmes (IFPPs) are interventions aimed at families in crisis, where there is an imminent risk of children entering care. They are programmes that work intensively with families to try to avoid out-of-home placement.
          .measurement
            .of-effect
              %label
                Effect
              .spot.measure.fill
              .spot.measure
              .spot.measure
            .negative.fill
              %label
                Negative
              .spot.measure
            .of-evidence
              %label
                Evidence
              .spot.measure.fill
              .spot.measure
              .spot.measure

app/views/governance/show.html.haml
.container.content_page#governance
  %h1= @page.title

  .indented
    = parse_markdown(@page.content)

    / .team.members_list.full_width
    /   .inner_container
    /     %h2 Development Team and Research Partner

    /     - @team_members.each do |tm|
    /       =link_to team_member_path(id: tm.slug), class: 'single_member_container' do
    /         .single_member
    /           .inner_container
    /             =tm.decorate.decorate_image
    /             .details
    /               %h3=tm.name
    /               .role=tm.try(:role)


    .board.members_list.full_width
      .inner_container
        %h2 Founding Board

        - @board_members.each do |bm|
          =link_to board_member_path(id: bm.slug), class: 'single_member_container' do
            .single_member
              .inner_container
                =bm.decorate.decorate_image
                .details
                  %h3=bm.name
                  .role=bm.try(:role)

    .members_list.full_width
      .inner_container
        %h2 Department for Education Steering Group
        %p The Centre is initially funded by the Department for Education. During its set up phase and prior to formal incorporation of the Centre as an independent organisation, the development team and research partner report on progress and value for money considerations to the Department’s Steering Group.

    .stakeholder.members_list.full_width
      .inner_container
        %h2 Stakeholder Panels
        %p We are working very closely with a wide range of stakeholders to advise on the Centre’s strategy, research priorities, and future products and services.

        - @stakeholder_panels.each do |sp|
          .single_member
            %h3=sp.title
            %p=sp.content

    .link
      %p
        Find out more about
        =link_to "who we are working with", section_page_path('working-with', 'whos-involved')
        and
        =link_to "what they have told us.", section_page_path('working-with', 'what-you-told-us')

app/views/who_we_are/show.html.haml
.container.content_page#who_we_are
  %h1= @page.title

  .indented
    = parse_markdown(@page.content)

    .team.members_list.full_width
      .inner_container
        %h2 Development Team and Research Partner

        - @team_members.each do |tm|
          =link_to team_member_path(id: tm.slug), class: 'single_member_container' do
            .single_member
              .inner_container
                =tm.decorate.decorate_image
                .details
                  %h3=tm.name
                  .role=tm.try(:role)


    .board.members_list.full_width
      .inner_container
        %h2 Founding Board

        - @board_members.each do |bm|
          =link_to board_member_path(id: bm.slug), class: 'single_member_container' do
            .single_member
              .inner_container
                =bm.decorate.decorate_image
                .details
                  %h3=bm.name
                  .role=bm.try(:role)

    .members_list.full_width
      .inner_container
        %h2 Department for Education Steering Group
        %p The Centre is initially funded by the Department for Education. During its set up phase and prior to formal incorporation of the Centre as an independent organisation, the development team and research partner report on progress and value for money considerations to the Department’s Steering Group.

    .stakeholder.members_list.full_width
      .inner_container
        %h2 Stakeholder Panels
        %p We are working very closely with a wide range of stakeholders to advise on the Centre’s strategy, research priorities, and future products and services.

        - @stakeholder_panels.each do |sp|
          .single_member
            %h3=sp.title
            %p=sp.content

    .link
      %p
        Find out more about
        =link_to "who we are working with", section_page_path('working-with', 'whos-involved')
        and
        =link_to "what they have told us.", section_page_path('working-with', 'what-you-told-us')